### ISSUE TITLE
What is the compatibility of this library with the different python versions?

### ISSUE THREAD

**Issue by loicgasser** [DevCycleHQ/python-server-sdk#18]
It is difficult to know with what python versions I can use this library and I am not seeing any build for different versions.
We purchased your product and wanted to integrate this library in our back-end.

**Comment by loicgasser** [comment]
3.8 at the moment, and we're upgrading to 3.10

**Comment by chris-hoefgen** [comment]
Hi @loicgasser, I have done some testing and confirmed that the current `python-server-sdk` release (1.2.2) works with both 3.10 and 3.11 without any issues.
