### ISSUE TITLE
Add a py.typed marker file so type annotations are available to downstream users

### ISSUE THREAD

**Issue by federicobond** [DevCycleHQ/python-server-sdk#26]
Hi, congrats on the new release! I noticed that the code contains annotations but mypy is not picking them because the package lacks a py.typed marker.

**Comment by cdruxerman** [comment]
Hi @federicobond I shared this with our team. I'll have them take a look and get back to you.

**Comment by federicobond** [comment]
Thank you!

**Comment by chris-hoefgen** [comment]
Hi @federicobond we have just created a 2.0.1 release which adds a `py.typed` marker file to the devcycle_python_sdk package which hopefully should solve the issue.

**Comment by federicobond** [comment]
Hi! Thank you for the quick turnaround. Just letting you know that I migrated my code to the new SDK and it works perfectly but mypy still complains with these errors when I follow the standard setup as described in the README: 

```
features.py:1: error: Module "devcycle_python_sdk" has no attribute "DevCycleCloudClient"  [attr-defined]
features.py:1: error: Module "devcycle_python_sdk" has no attribute "DevCycleCloudOptions"  [attr-defined]
```

I am not an expert on mypy so I am not sure how to make those re-exports work. I tried exporting with "as" and defining an `__all__` without success. 

If I import these names from their original packages it works though.

**Comment by chris-hoefgen** [comment]
@federicobond We don't have a quick solution for this at the moment but we are working on a major update to the Python SDK right now that should release in the next week or so. I have created a ticket for that project to improve MyPy support for that release.

**Comment by chris-hoefgen** [comment]
@federicobond We have just released v3.0.0 of the SDK with some major updates, including substantial support for static typing. We have done some tests using the SDK in VSCode with MyPy and it does't seem to generate any of the errors you were encountering earlier, but we also understand everyone has different development setups.

**Comment by federicobond** [comment]
Awesome! I was just testing out the new DevCycleLocalClient and I am bumping into this error, though:

> FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.11/site-packages/devcycle_python_sdk/bucketing-lib.release.wasm'

I believe the .wasm files may not be correctly included in the release artifacts.

**Comment by chris-hoefgen** [comment]
thanks for letting us know, we'll look into that immediately

**Comment by chris-hoefgen** [comment]
Ok, we now have 3.0.1 which should resolve that issue

**Comment by federicobond** [comment]
Thanks Chris! 3.0.1 already running in production with local bucketing here. I think we can close this issue.

**Comment by chris-hoefgen** [comment]
great news.  Keep us posted if there are any issues with the new local bucketing SDK!
