### ISSUE TITLE
Implement an OpenFeature provider

### ISSUE THREAD

**Issue by federicobond** [DevCycleHQ/python-server-sdk#59]
Hi! I'm working on getting the first stable release of the OpenFeature Python SDK out. I also have a project that uses DevCycle for powering its feature flags. I would like to use it as guinea pig to make sure the solution works end-to-end.

If you are interested in writing an OpenFeature provider, I can offer help with reviewing the code and beta testing it.

**Comment by jonathannorris** [comment]
Hey @federicobond, happy to have you help with an OpenFeature Python SDK! We do have plans to start implementing all these OpenFeature Providers for our various SDKs (likely in Oct/Nov), we currently just have the Node SDK one as a reference: https://docs.devcycle.com/sdk/server-side-sdks/node/node-openfeature

The likely next ones we will publish are Web / Go, but Python would likely be next with Java.

Take a look at the NodeJS Provider first. There were a couple of complexities we had to manage for User Data and Custom Data: https://github.com/DevCycleHQ/js-sdks/blob/main/sdk/openfeature-nodejs-provider/src/DevCycleProvider.ts

Happy to let you know once we start working on it, but if you decide to take a run at it, we are happy to review and go through the process to get it officially published.

**Comment by federicobond** [comment]
Awesome! I'd like to limit my volunteer work to the OpenFeature project for the moment but let me know when you start working on it and I would be happy to provide assistance.

**Comment by chris-hoefgen** [comment]
Hi @federicobond , we actually have an active PR for this now: https://github.com/DevCycleHQ/python-server-sdk/pull/60

We would love some feedback on it if you have a chance!

**Comment by federicobond** [comment]
Awesome! I'll check it out.

**Comment by federicobond** [comment]
@chris-hoefgen if you can publish a beta version to PyPI I can try it this week in one of my projects.

**Comment by chris-hoefgen** [comment]
Likely we will just do a full release this weak with a minor version bump since the code is all additive. I'll let you know once it is live.

**Comment by rob-odwyer** [comment]
Hi @federicobond - we've just released `v3.4.0` of our Python SDK, which includes an OpenFeature provider:
https://pypi.org/project/devcycle-python-server-sdk/

The docs are here if you'd like to give it a try: https://docs.devcycle.com/sdk/server-side-sdks/python/python-openfeature
And there's a [tested example in the repo](https://github.com/DevCycleHQ/python-server-sdk/blob/main/example/openfeature_example.py) if that's helpful.

**Comment by federicobond** [comment]
Already running in prod with the OF provider. Everything looking good so far!
